[package]
name = "byecache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oneshot = "0.1.3"
sudo = "0.6.0"
walkdir = "2.3.2"
